### ISSUE TITLE
Elastic agent registration and installation shell script tested and verified.

### ISSUE THREAD

**Issue by Udayel** [aws-ia/terraform-elastic-cloud#16]
For the agent_install script to work we need the following env vars set on the EC2. So all that’s left to do now is for you to set these variables using whatever approach is the easiest with terraform, or alternatively replace them in the script if that’s better.

We can below variables from Elastic deployment as output and set as an input variables here.

export FLEET_URL="CHANGE ME"
export ELASTICSEARCH_PASSWORD="CHANGE ME"
export KIBANA_URL="CHANGE ME"

Above variables and below script will go to install_elastic_agent.sh bash script and we can run script as a userdata. 

#!/bin/bash
install_elastic_agent() {
  # "jq" needs to be installed on the host 
  apt-get install jq -y
  count=0
  MAX_ATTEMPTS=6
  echo "creating API Key"
  policy_id="unknown"
  while [[ $count -lt $MAX_ATTEMPTS ]]; do
    sleep 10
    echo $date
    response=$(curl -XGET -H "kbn-xsrf: true" -u elastic:$ELASTICSEARCH_PASSWORD -w "%{http_code}" -s "${KIBANA_URL}/api/fleet/agent_policies" -H 'Content-Type: application/json')
    echo "Response: "
    echo $response
    http_code=${response: -3}
    content=$(echo $response | rev | cut -c 4- | rev)
    echo "http code: "
    echo $http_code
    echo "content: "
    echo $content
    if [[ $code != 200  ]] ; then
      echo $content | jq
      policy_id=$( jq -r '.items[] | select(.name == "Default policy") | .id' <<< "${content}" )
      echo policy_id
      echo "http code is 200, Policy ID fetched succesfully"
      break
    fi
  done
  while [[ $count -lt $MAX_ATTEMPTS ]]; do
    sleep 10
    echo $date
    response=$(curl -XGET -H "kbn-xsrf: true" -u elastic:$ELASTICSEARCH_PASSWORD -w "%{http_code}" -s "${KIBANA_URL}/api/fleet/enrollment-api-keys" -H 'Content-Type: application/json')
    echo "Response: "
    echo $response
    http_code=${response: -3}
    content=$(echo $response | rev | cut -c 4- | rev)
    echo "http code: "
    echo $code
    echo "content: "
    echo $content
    if [[ $code != 200  ]] ; then
      echo $content | jq
      api_key=$( jq -r --arg policy_id "${policy_id}" '.list[] | select(.policy_id == $policy_id) | .api_key' <<< "${content}" )
      echo $api_key
      echo "http code is 200, API Key fetched successfully"
      break
    fi
  done
  
  echo "Downloading Elastic Agent..."
  curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.15.1-linux-x86_64.tar.gz
  tar xzvf elastic-agent-7.15.1-linux-x86_64.tar.gz
  cd elastic-agent-7.15.1-linux-x86_64
  sudo ./elastic-agent install -f --url=${FLEET_URL} --enrollment-token=$api_key
  echo "Elastic Agent has been downloaded."
}
_main() {
 install_elastic_agent
}
_main "$@"

**Comment by batpur** [comment]
Added this in https://github.com/aws-ia/terraform-elastic-cloud/pull/22
